version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: papersearch-frontend
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    container_name: papersearch-backend
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MONGO_HOST=localhost 
      - MONGO_PORT=27017
      - MONGO_DATABASE=papersearch
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - CORS_ORIGINS=http://localhost:3090,http://${CORS_IP}:3090
    volumes:
      - ./backend/logs:/app/logs